### ISSUE TITLE
Make a big binary wheel including dependencies

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/python-casacore#145]
A lot of new astronomers are struggling with the installation of python-casacore. And to be honest, it is not easy. First, you need to install casacore with the right flags, then you need to compile the python code and point to the right locations. Additionally, there is the problem that you might mix up the various boost or casacore libraries during runtime, resulting in weird errors. 

I think all of this could be solved if we compile all the dependencies in statically and bundle this in a binary wheel. I don't have a lot of experience with this, but this is how packages like Tensorflow operate (although they still have CUDA compatibility issues).

**Comment by gijzelaerr** [comment]
looks like auditwheel does what we want https://github.com/pypa/auditwheel

**Comment by ludwigschwardt** [comment]
Have a look at ska-sa/spead2, which is also C++ and now builds `manylinux2010` wheels.

**Comment by gijzelaerr** [comment]
Ludwig, you are making my day.

**Comment by gijzelaerr** [comment]
trying to make this now, but centos6 comes with wcslib 4.3, while casacore has a minimum requirement of 4.7. @gervandiepen how critical is it to have this version? can we hack around to get it working with 4.3?

**Comment by tammojan** [comment]
Casacore needs to do some memory management on internal wcslib structures. For example in  coordinates/Coordinates/FITSCoordinateUtil.cc . I don't think casacore depends on new functionality in the newer wcslib versions, although it might be less thread safe in older versions.

It is probably possible to make casacore work with older wcslib by adding sufficient `#ifdef`s on the wcslib version, like https://github.com/casacore/casacore/blob/master/coordinates/Coordinates/FITSCoordinateUtil.cc#L955

I'd say try to build and test with 4.3 and see what happens.

**Comment by gervandiepen** [comment]
I recall that older versions have a slightly different API, but I'm not
sure. You can make a local change and try to use 4.3.
4.3 is really old; the current wcslib version is 6.2!!

**Comment by gijzelaerr** [comment]
building with 4.3 fails:
```
[ 85%] Building CXX object meas/MeasUDF/test/CMakeFiles/tFrequencyEngine.dir/tFrequencyEngine.cc.o
/casacore/coordinates/Coordinates/FITSCoordinateUtil.cc: In member function ‘casacore::Bool casacore::FITSCoordinateUtil::frequencySystemFromWCS(casacore::LogIO&, casacore::MFrequency::Types&, casacore::String&, const wcsprm&) const’:
/casacore/coordinates/Coordinates/FITSCoordinateUtil.cc:1427:21: error: ‘const struct wcsprm’ has no member named ‘velref’
             if (wcs.velref==0) { // velref was also not given
                     ^~~~~~
/casacore/coordinates/Coordinates/FITSCoordinateUtil.cc:1434:25: error: ‘const struct wcsprm’ has no member named ‘velref’
          Int vref = wcs.velref;
                         ^~~~~~
make[2]: *** [coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/FITSCoordinateUtil.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by gijzelaerr** [comment]
I've added my initial work on a wheel constructing docker file:

https://github.com/casacore/python-casacore/blob/master/.travis/wheel.docker

**Comment by gijzelaerr** [comment]
I've updated the wheel image to build `wcslib` and `boost` ourselves, which all works. We now have another issue. The `manylinux2010` container actually doesn't contain a `libpython` shared library since it is considered to be bad practice to link to this. Casacore fails to build without a libpython shared library. i'm not sure what is wise here or how to proceed.

https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1

**Comment by ludwigschwardt** [comment]
If you read the [docs](https://docs.brew.sh/Python-for-Formula-Authors) on packaging Python bindings on Homebrew, they link to this helpful [post](https://blog.tim-smith.us/2015/09/python-extension-modules-os-x/).

Just remove the `-lpython` from the linker invocation but make sure you have the `-shared` flag. This ignores undefined symbols (at least on Linux). They will get resolved when you load the python module at runtime.

**Comment by gijzelaerr** [comment]
this is working now and good to go!
